# cluster specific values
cluster:
  # specify cluster name
  name: ""

  # specify cluster description
  description: ""

# specify cloud credential secret name, do not need to be provided if using custom driver
cloudCredentialSecretName: ""
